<?php

return [
    'groups' => [
        'funziona' => [
            'L\'importante è che funzioni, i fiorellini possono aspettare.',
            'Prima il codice, poi le cornicette.',
            'Se gira, è già bello.',
            'Funziona? Allora è arte.',
            'Meno fronzoli, più risultati.',
            'Le cornicette non fanno deploy.',
            'Il design passa, il bug resta.',
            'Brutto ma operativo.',
            'Pixel dopo, logica subito.',
            'La bellezza è soggettiva, il funzionamento no.',
            'Niente fiorellini, solo sostanza.',
            'Se compila, è elegante abbastanza.',
            'Le cornicette non risolvono i problemi.',
            'Meglio utile che carino.',
            'Estetica rimandata, efficienza consegnata.',
            'Prima funziona, poi si abbellisce (forse).',
            'Senza fronzoli, ma senza crash.',
            'Il minimalismo per necessità.',
            'Codice solido, grafica timida.',
            'Le animazioni non aggiustano i bug.',
            'Brutto fuori, affidabile dentro.',
            'La UI è un\'opinione, la logica è un fatto.',
            'Fiorellini off, funzionalità on.',
            'Se serve, basta.',
            'Più sostanza, meno glitter.',
            'L\'arte è opzionale, l\'esecuzione no.',
            'Non è bello, ma lavora sodo.',
            'Correggi prima, decora poi.',
            'Grafica spartana, risultati pieni.',
            'Niente orpelli, solo output.',
            'Il vero stile è non rompersi.',
            'Funziona quindi vale.',
            'Meglio rapido che raffinato.',
            'Le cornicette non fanno KPI.',
            'Zero fiorellini, cento per cento operatività.',
            'Estetica in backlog.',
            'Il bello verrà... forse.',
            'Codice prima, colori dopo.',
            'Se non si rompe, è già design.',
            'Più click utili, meno pixel inutili.',
            'Niente fronzoli, niente scuse.',
            'L\'essenziale è invisibile... ma funziona.',
            'Brutto ma sincero.',
            'Le ombre non salvano le funzioni.',
            'Funziona oggi, abbelliamo domani.',
            'La grafica non compensa la logica.',
            'Meno estetica, più etica del codice.',
            'Se serve allo scopo, è perfetto.',
            'Niente glitter, solo deliver.',
            'La priorità è farlo andare, non farlo sfilare.',
        ],
        'sarcastici' => [
            'Tranquilli, la grafica la aggiungiamo nella versione 2042.',
            'Non sarà bello, ma almeno non funziona... ah no, funziona.',
            'Ho tolto i fiorellini per migliorare le performance.',
            'Se vuoi le cornicette, apri PowerPoint.',
            'Qui si lavora, non si arreda.',
            'Design? Mai sentito, però gira.',
            'Sì, è brutto. No, non mi interessa.',
            'Il minimalismo spinto... dalla fretta.',
            'Più che brutto, è funzionale avanzato.',
            'Le animazioni sono state licenziate per inutilità.',
            'Il designer è in ferie da sempre.',
            'Non è un bug, è bruttezza intenzionale.',
            'Se cerchi stile, hai sbagliato tool.',
            'Il colore dominante è "default".',
            'Nessun pixel è stato abbellito durante lo sviluppo.',
            'Le cornicette sono state sacrificate agli dei del deploy.',
            'Sì, sembra anni \'90. È voluto (più o meno).',
            'L\'estetica è stata ottimizzata via rm -rf.',
            'Più grigio di così si muore... ma funziona.',
            'UX: Usalo e basta.',
            'Ho scelto il font "quello che c\'era".',
            'Se è brutto, almeno è coerente.',
            'Il CSS ha deciso di non partecipare.',
            'Bello non è, utile sì: fatevene una ragione.',
            'Il design è un optional non installato.',
            'Le ombre le lasciamo ai filosofi.',
            'Se non ti piace, chiudi gli occhi.',
            'La palette colori è "errore di default".',
            'Funziona così bene che non serve guardarlo.',
            'Le cornicette causavano ansia al codice.',
            'Non giudicare un tool dalla sua UI.',
            'L\'estetica è in fase di beta eterna.',
            'Qui si compila, non si decora.',
            'Più che brutto, è... essenziale estremo.',
            'Il designer? Licenziato per eccesso di gusto.',
            'Le icone sono state sostituite da testo onesto.',
            'Non è spartano, è minimalismo aggressivo.',
            'La grafica è un suggerimento, non una promessa.',
            'Ho evitato i fiorellini per non distrarti dal successo.',
            'Se funziona, chi guarda la grafica?',
            'Il layout è stato progettato... dal caso.',
            'L\'eleganza è sopravvalutata.',
            'Il bello passa, il deploy resta.',
            'Più utility che vanità.',
            'Non è carino, è efficiente.',
            'Il design è stato sostituito da buon senso.',
            'Se ti serve estetica, c\'e Instagram.',
            'Qui conta il risultato, non la passerella.',
            'La UI è timida, ma lavora sodo.',
            'Non sarà bello, ma almeno non è PowerPoint.',
        ],
        'corporate' => [
            'Focus sulla funzionalità, estetica in roadmap.',
            'Priorità alla delivery, design iterativo.',
            'Soluzione pragmatica, miglioramenti continui.',
            'Value first, styling later.',
            'Efficienza operativa sopra l\'estetica.',
            'Output prima dell\'outfit.',
            'Funzionalità core, ottimizzazione progressiva.',
            'MVP oggi, design domani.',
            'Performance-driven, design-aware.',
            'Risultati concreti, interfaccia essenziale.',
            'Approccio lean anche nella grafica.',
            'Design minimale, impatto massimo.',
            'Execution first mindset.',
            'Deliverable funzionante, estetica scalabile.',
            'Pragmatismo visivo, solidità logica.',
            'Funziona già, migliora sempre.',
            'Ottimizzazione continua dell\'esperienza.',
            'Solido backend, frontend evolutivo.',
            'Priorità al valore, non ai dettagli decorativi.',
            'Design essenziale, funzionalità completa.',
            'Time-to-value ridotto, estetica differita.',
            'Soluzione concreta, interfaccia snella.',
            'Efficienza prima della rifinitura.',
            'Core stabile, UI incrementale.',
            'Sostanza sopra forma.',
            'Delivery-oriented, design-friendly.',
            'Funzionalità garantita, estetica migliorabile.',
            'MVP solido, UX in evoluzione.',
            'Risultati prima della rifinitura grafica.',
            'Implementazione rapida, design iterativo.',
            'Architettura robusta, estetica modulare.',
            'Valore immediato, perfezionamento continuo.',
            'Performance prima del polish.',
            'Output concreto, design sostenibile.',
            'Efficienza come baseline.',
            'UI minimale, ROI massimo.',
            'Funzionalità validata, estetica ottimizzabile.',
            'Delivery efficace, design incrementale.',
            'Value-driven development.',
            'Essenziale oggi, raffinato domani.',
            'Stabilità prima dell\'estetica.',
            'Funziona ora, migliora nel tempo.',
            'Core first approach.',
            'Iterazione continua anche sulla grafica.',
            'Priorità all\'utilizzo reale.',
            'Soluzione pronta, estetica in backlog.',
            'Efficienza operativa, design progressivo.',
            'Funzionalità completa, interfaccia leggera.',
            'Approccio pragmatico alla UX.',
            'Delivery affidabile, estetica evolutiva.',
        ],
    ],
];
